### ISSUE TITLE
Extract function

### ISSUE THREAD

**Issue by michalstefanext** [projectnessie/cel-java#80] opened 2022-01-06 17:50 UTC
I am not able to find/figure out, how to use "extract" function (https://cloud.google.com/iam/docs/conditions-attribute-reference#extract). Would you be able to provide some small example or give me some direction at least please? Right now, whatever I try, I always get:

Exception in thread "main" org.projectnessie.cel.tools.ScriptCreateException: check failed: ERROR: :1:22: undeclared reference to 'extract' (in container '')

for this:
Script script = scriptHost.buildScript("assertion.arn.extract('{account_arn}/assumed-role')")

I simply am unable to find out, how to define the identifier (account_arn) of extract method.

Thanks!

**Comment by laurentgo** [comment] 2022-01-06 17:55
The function is not part of CEL standard definition and it is up to you to implement it if you want to reproduce IAM behavior

**Comment by laurentgo** [comment] 2022-01-06 17:56
(closing since it is not an issue)

**Closed by laurentgo** 2022-01-06 17:55 UTC

**Comment by michalstefanext** [comment] 2022-01-07 07:47
I see, thank you.
